id: I9CDC2D00
legacy_id: P002888
ocr_import_info:
  bdrc_scan_id: W30340
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T13:42:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:32:41.373346+00:00'
last_modified: 2022-09-03 19:33:37.343871
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30340
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30340
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཁོན་ལུགས་ཕུར་པའི་རྣམ་བཤད།
  author: ས་སྐྱ་ཁྲི་ཆེན ༢༣་ཀུན་དགའ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.8322343713118712
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I6081:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6081
      total_pages: 994
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6081.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8322343713118712
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
