id: I9CDC2D00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:43:23+00:00'
last_modified: '2022-06-07T15:24:56.231111+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30340
  title: འཁོན་ལུགས་ཕུར་པའི་རྣམ་བཤད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6864':
      image_group_id: I6081
      title: ''
      total_pages: 994
      order: 1
      base_file: 6864.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
