id: P002888
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:26:32.214352
source_metadata:
  id: bdr:W30340
  title: འཁོན་ལུགས་ཕུར་པའི་རྣམ་བཤད
  author: ''
  volumes:
    676595db067c4b21bf1ad79018e653fa:
      image_group_id: I6081
      title: ''
      volume_number: 1
      total_pages: 994
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
